<?php use Aibid\Http\View as V; ?>
<div class="page-heading"><div><span class="eyebrow">VISTA GENERAL</span><h1>Tu operación, al día</h1><p>Licencias, clientes y próximos vencimientos en un solo lugar.</p></div><?php if ($actor->canWrite()): ?><a class="btn btn-primary" href="/admin/licenses/new">＋ Emitir licencia</a><?php endif; ?></div>
<div class="metric-grid">
<?php foreach ([['Licencias emitidas',$stats['licenses'],'Derechos registrados','/admin/licenses'],['Clientes activos',$stats['customers'],'Relaciones comerciales','/admin/customers'],['Licencias perpetuas',$stats['perpetual'],'Uso sin vencimiento','/admin/licenses?type=perpetual'],['Vencen en 30 días',$stats['expiring'],'Suscripciones por revisar','/admin/licenses?expiry=soon']] as [$label,$value,$description,$link]): ?>
<a href="<?= V::escape($link) ?>" class="metric-card"><span><?= $label ?></span><strong><?= (int) $value ?></strong><small><?= $description ?><span aria-hidden="true">↗</span></small></a>
<?php endforeach; ?>
</div>
<div class="row g-4 mt-1"><div class="col-xl-8"><section class="panel"><div class="panel-heading"><div><h2>Licencias recientes</h2><p>Las últimas emisiones de tu equipo.</p></div><a href="/admin/licenses" class="text-link">Ver todas →</a></div>
<?php if (!$stats['recent']): ?><div class="empty-state"><div class="empty-symbol" aria-hidden="true">◇</div><h3>El comienzo de una operación ordenada</h3><p>Registra tu primer cliente y emite una licencia para empezar.</p><?php if ($actor->canWrite()): ?><a class="btn btn-outline-primary" href="/admin/customers/new">Registrar cliente</a><?php endif; ?></div>
<?php else: ?><div class="table-responsive"><table class="table"><thead><tr><th>Cliente / producto</th><th>Modalidad</th><th>Vencimiento</th><th><span class="visually-hidden">Detalle</span></th></tr></thead><tbody><?php foreach ($stats['recent'] as $license): ?><tr><td><strong><?= V::escape($license['customer_name']) ?></strong><small class="cell-sub"><?= V::escape($license['product_name']) ?></small></td><td><span class="tag"><?= $license['license_type'] === 'perpetual' ? 'Perpetua' : 'Suscripción' ?></span></td><td><?= $license['expires_at'] === null ? 'Sin vencimiento' : V::escape(V::date($license['expires_at'])) ?></td><td><a href="/admin/licenses/<?= V::escape($license['id_text']) ?>" class="text-link">Ver →</a></td></tr><?php endforeach; ?></tbody></table></div><?php endif; ?></section></div>
<div class="col-xl-4"><section class="panel activity-panel"><div class="panel-heading"><div><h2>Actividad reciente</h2><p>Un registro de cada paso.</p></div></div><ol class="activity-list"><?php foreach ($stats['events'] as $event): ?><li><strong><?= V::escape(V::action($event['operation'])) ?></strong><span><?= V::escape($event['actor_name'] ?? 'Sistema') ?></span><small><?= V::escape(V::date($event['occurred_at'])) ?></small></li><?php endforeach; ?></ol><a href="/admin/audit" class="text-link">Consultar auditoría →</a></section></div></div>
<section class="brand-banner"><img src="/assets/brand/logo-h.svg" alt="AIBID"><div><strong>Derechos claros. Continuidad para tus clientes.</strong><p>Las licencias perpetuas conservan su uso; el mantenimiento se registra por separado.</p></div></section>
