<?php use Aibid\Http\View as V; $availableProducts = array_values(array_filter($products, fn($product) => $product['state']==='active')); $selectedProduct=$availableProducts[0]['product_id']??''; ?>
<div class="page-heading"><div><a class="text-link" href="/admin/licenses">← Licencias</a><h1 class="mt-3">Emitir una licencia</h1><p>Define los derechos del cliente y genera su clave comercial.</p></div></div>
<?php if (!$customers || !$availableProducts): ?><div class="alert alert-info">Necesitas un cliente y un producto activos para emitir una licencia. <a href="/admin/customers/new">Registrar cliente</a></div><?php else: ?>
<form method="post" action="/admin/licenses/create" id="license-form"><div class="row g-4"><div class="col-xl-8"><section class="panel form-panel"><?php V::fields($csrf); ?>
<div class="section-heading"><span>01</span><h2>Cliente y producto</h2></div><div class="row g-4"><div class="col-md-6"><label for="customer_id" class="form-label">Cliente</label><select class="form-select" name="customer_id" id="customer_id" required><option value="">Selecciona un cliente</option><?php foreach ($customers as $customer): ?><option value="<?= V::escape($customer['id_text']) ?>"><?= V::escape($customer['display_name']) ?></option><?php endforeach; ?></select></div><div class="col-md-6"><label for="product_id" class="form-label">Producto</label><select class="form-select" name="product_id" id="product_id" required><?php foreach ($availableProducts as $product): ?><option value="<?= V::escape($product['product_id']) ?>"><?= V::escape($product['display_name']) ?></option><?php endforeach; ?></select></div></div>
<div class="section-heading mt-5"><span>02</span><h2>Modalidad y vigencia</h2></div><div class="row g-3"><div class="col-md-6"><label class="choice-card"><input type="radio" name="license_type" value="perpetual" checked><span><strong>Perpetua</strong><small>Pago único · Uso sin vencimiento</small></span></label></div><div class="col-md-6"><label class="choice-card"><input type="radio" name="license_type" value="subscription"><span><strong>Suscripción</strong><small>Vigencia definida · 15 días de tolerancia</small></span></label></div></div>
<div class="mt-4" data-license-type="perpetual"><label for="entitled_release_until" class="form-label">Versiones publicadas hasta <span class="optional">UTC</span></label><input class="form-control" type="datetime-local" id="entitled_release_until" name="entitled_release_until" value="<?= V::escape($now->format('Y-m-d\TH:i')) ?>" required><div class="form-text">Fecha de corte de las versiones incluidas en la compra. No vence el derecho de uso.</div></div>
<div class="mt-4" data-license-type="subscription" hidden><label for="expires_at" class="form-label">Vencimiento exclusivo <span class="optional">UTC</span></label><input class="form-control" type="datetime-local" id="expires_at" name="expires_at" disabled><div class="form-text">La tolerancia dura 15 días completos después de este instante.</div></div>
<div class="section-heading mt-5"><span>03</span><h2>Módulos autorizados</h2></div>
<?php foreach ($availableProducts as $product): ?><div class="feature-grid" data-product="<?= V::escape($product['product_id']) ?>" <?= $product['product_id']!==$selectedProduct?'hidden':'' ?>><?php foreach ($capabilities as $feature): if($feature['product_id']!==$product['product_id'])continue; ?><label class="feature-choice"><input class="form-check-input" type="checkbox" name="features[]" value="<?= V::escape($feature['capability_key']) ?>" data-requires="<?= V::escape($feature['requires_keys']) ?>" <?= $product['product_id']!==$selectedProduct?'disabled':'' ?>><span><?= V::escape($feature['display_name']) ?><?php if($feature['requires_keys']): ?><small>Requiere <?= V::escape($feature['requires_keys']) ?></small><?php endif; ?></span></label><?php endforeach; ?></div><?php endforeach; ?>
<div class="section-heading mt-5"><span>04</span><h2>Referencia de la emisión</h2></div><div class="stack-form"><div><label for="reference" class="form-label">Referencia comercial <span class="optional">opcional</span></label><input class="form-control" name="reference" id="reference" maxlength="190" placeholder="Pedido, factura o acuerdo"></div><div><label for="reason" class="form-label">Motivo / nota de autorización</label><textarea class="form-control" name="reason" id="reason" rows="2" maxlength="500" required></textarea></div></div>
<div class="form-footer"><a class="btn btn-outline-secondary" href="/admin/licenses">Cancelar</a><button class="btn btn-primary" type="submit">Emitir y mostrar clave</button></div></section></div>
<div class="col-xl-4"><aside class="panel form-panel sticky-summary"><span class="eyebrow">CONDICIONES DE EMISIÓN</span><h2 class="mt-3">Derechos claros desde el inicio</h2><ul class="check-list"><li>Una instalación por licencia</li><li>Usuarios ilimitados</li><li>Sin límites de documentos ni bibliotecas</li><li>Módulos seleccionados por producto</li></ul><div class="note-box">La perpetua se emite sin mantenimiento incluido. Cualquier compra de mantenimiento se registra después, por separado.</div><p class="small text-secondary mt-4 mb-0">La clave comercial se mostrará una sola vez. Guarda y entrega ese valor por un canal seguro.</p></aside></div></div></form><?php endif; ?>
